services:
  daemon:
    image: bqa-daemon:0.1.0
    build:
      context: .
      dockerfile: ./infra/Dockerfile
      target: prod
      args:
        - UID=1106
        - GID=1108
    volumes:
      - ./src:/app/src
      - ./secrets:/app/secrets
      - ./jobs:/jobs
      - ./certs:/app/certs
    container_name: bqa-daemon-container
    env_file: ./.env.prod
    restart: unless-stopped
