[project]
name = "bqa-daemon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "paramiko>=4.0.0",
    "protobuf>=6.33.4",
    "temporalio>=1.21.1",
]
